fixes:
   - "/ansible_collections/lowlydba/sqlserver/::"

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
    patch:
      default:
        # basic
        target: 90%
  ignore:
    - "tests/**"
