# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: lowlydba
name: sqlserver
version: 2.7.0
readme: README.md
authors:
  - John McCall (github.com/lowlydba)
description: Ansible collection using PowerShell to configure and maintain SQL Server.
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - sqlserver
  - mssql
  - database
repository: https://github.com/LowlyDBA/lowlydba.sqlserver
documentation: https://lowlydba.github.io/lowlydba.sqlserver
homepage: https://github.com/LowlyDBA/lowlydba.sqlserver
issues: https://github.com/LowlyDBA/lowlydba.sqlserver/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - .gitattributes
  - changelogs/.plugin-cache.yaml
  - .vscode/
  - .github/
  - MAINTAINING.md
  - REVIEW_CHECKLIST.md
