name: Collection Docs
concurrency:
  group: docs-${{ github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 13 * * *'

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      ansible-ref: devel  # TODO: consider milestone
      init-lenient: false
      init-fail-on-error: true
