name: GitHub Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to release"
        required: true

env:
  GHP_BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases and tags
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec # v6
        with:
          python-version: 3.8

      - name: Install PyYaml
        run: pip install pyyaml

      - name: Publish to Galaxy
        uses: artis3n/ansible_galaxy_collection@325f5822aea7846e7d46a2522456898e9295acf2 # v3.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}

      - name: Validate version is published to Galaxy
        run: curl --head -s -f -o /dev/null https://galaxy.ansible.com/download/lowlydba-sqlserver-${GITHUB_EVENT_INPUTS_VERSION}.tar.gz
        env:
          GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}

      - name: Build release description
        shell: python
        run: |
          import os
          import yaml

          ver = '${{ github.event.inputs.version }}'
          ver_anchor = str.replace(ver, '.', '-')

          with open('changelogs/changelog.yaml', 'r') as s:
              ri = yaml.safe_load(s)

          if ('release_summary' not in ri['releases'][ver]['changes']):
            summary = 'No release summary available.'
          else:
            summary = ri['releases'][ver]['changes']['release_summary']

          reldate = ri['releases'][ver]['release_date']

          description = '''## Summary
          Released: %s

          %s

          ---

          View the [complete changelog](https://github.com/lowlydba/lowlydba.sqlserver/blob/main/CHANGELOG.rst#v%s) to see all changes.

          View the [full documentation for release ${{ github.event.inputs.version }}](${{ env.GHP_BASE_URL }}/tag/${{ github.event.inputs.version }}).
          ''' % (reldate, summary, ver_anchor)

          with open(os.environ['GITHUB_ENV'], 'a') as e:
              e.write("RELEASE_DESCRIPTION<<EOF\n%s\nEOF" % description)

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ env.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ env.RELEASE_DESCRIPTION }}
